[database]
host = "localhost"
port = 5432
username = "postgres"
password = "postgres"
database = "semantic_gallery"

[embedding]
model_path = "/home/felix/projects/semantic-gallery/tmp/models/clip/model.safetensors"
tokenizer_path = "/home/felix/projects/semantic-gallery/tmp/models/clip/tokenizer.json"
dimension = 1536
use_gpu = false

[storage]
media_path = "media"
