[database]
host = "localhost"
port = 5432
username = "postgres"
password = "postgres"
database = "semantic_gallery"

[embedding]
# TODO: use later
model_path = "docker-compose.yml"
dimension = 1536

[storage]
media_path = "media"
