services:
  postgres:
    image: ankane/pgvector:latest
    container_name: semantic_gallery_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: semantic_gallery
      POSTGRES_PASSWORD: semantic_gallery_password
      POSTGRES_DB: semantic_gallery
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # TODO: Add migration management via sqlx
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U semantic_gallery -d semantic_gallery"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
